name: Hexo Deploy

on:
  push:
    branches:
      - blog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup NPM & Hexo environment
        run: |
          npm install hexo-cli -g
          npm ci


      - name: Hexo generate & Deploy To Github Pages
        run: |
          hexo clean
          hexo douban -bm
          hexo 123
          abcd

      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hongkong.aliyuncs.com"
          access-key-id: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}

      - name: Deply To OSS
        run: |
          ossutil cp -r -u -j 24 public oss://lyz05blog/ 
