name: Workflow Notifications

on:
  workflow_run:
    workflows: [Hexo Deploy]
    types:
      - completed

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      # 检查工作流运行结果
      - name: Check Workflow Status
        id: check_status
        uses: actions/github-script@v7
        with:
          script: |
            const status = context.payload.workflow_run.conclusion;
            if (status === 'failure') {
              return { failure: true };
            } else {
              return { failure: false };
            }

      # 发送通知，不论结果如何
      - name: Sending message failure
        if: steps.check_status.outputs.failure
        env:
          key: ${{ secrets.sckey }}
          title: 博客部署失败
          content: 博客部署失败，请检查日志。
        run: 
          curl -d "title=$title&content=$content" "http://www.pushplus.plus/send/$key"

      
      - name: Sending message success
        if: steps.check_status.outputs.failure == false
        env:
          key: ${{ secrets.sckey }}
          title: 博客部署成功
          content: 博客部署成功
        run: 
          curl -d "title=$title&content=$content" "http://www.pushplus.plus/send/$key"